name: CI/CD Workflow

on:
  push:
    branches:
      - main  # Para monitorar o branch principal

jobs:
  build:
    name: Build and Test Docker Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        run: |
          docker buildx install  # Instalando o Buildx
          docker buildx use --default  # Configurar Buildx como padrão

      - name: Build Docker Image
        run: docker build -t password-generator .

      - name: Run Tests
        run: docker run --rm password-generator

      - name: Package Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: output.txt  # Alterando para o arquivo correto gerado

      - name: List Artifacts
        run: |
          echo "List of available artifacts:"
          ls -al
