name: CI/CD Workflow

on:
  push:
    branches:
      - main  # Para monitorar o branch principal

jobs:
  build:
    name: Build and Test Docker Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        run: docker buildx install  # Instalando o Buildx

      - name: Build Docker Image
        run: docker build -t password-generator .

      - name: Run Tests
        run: docker run --rm password-generator > output.txt

      - name: Check for output.txt and create artifact
        run: |
          if [ ! -f output.txt ]; then
            echo "output.txt not found, creating..."
            docker run --rm password-generator > output.txt
          else
            echo "output.txt already exists, skipping generation."
          fi
          tar -czf artifacts.tar.gz output.txt
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: artifacts.tar.gz
